require_relative('../models/customer')
require_relative('../models/film')
require_relative('../models/ticket')

require('pry')

Customer.delete_all()
Film.delete_all()
Ticket.delete_all()

customer1 = Customer.new({"name" => "Jan", "funds" => 20})
customer1.save()
customer2 = Customer.new({"name" => "Celine", "funds" => 40})
customer2.save()
customer3 = Customer.new({"name" => "Norma", "funds" => 10})
customer3.save()
customer4 = Customer.new({"name" => "Kate", "funds" => 25})
customer4.save()
customer5 = Customer.new({"name" => "Penny", "funds" => 15})
customer5.save()

film1 = Film.new({"title" => "Jason Bourne", "price" => 5})
film1.save()
film2 = Film.new({"title" => "Dirty Dancing", "price" => 3})
film2.save()
film3 = Film.new({"title" => "Black Panther", "price" => 8})
film3.save()

ticket1 = Ticket.new({"customer_id" => customer1.id, "film_id" => film1.id })
ticket1.save()
ticket2 = Ticket.new({"customer_id" => customer1.id, "film_id" => film2.id })
ticket2.save()
ticket3 = Ticket.new({"customer_id" => customer2.id, "film_id" => film3.id })
ticket3.save()
ticket4 = Ticket.new({"customer_id" => customer3.id, "film_id" => film3.id })
ticket4.save()
ticket5 = Ticket.new({"customer_id" => customer4.id, "film_id" => film1.id })
ticket5.save()
ticket6 = Ticket.new({"customer_id" => customer4.id, "film_id" => film3.id })
ticket6.save()
ticket7 = Ticket.new({"customer_id" => customer5.id, "film_id" => film1.id })
ticket7.save()
ticket8 = Ticket.new({"customer_id" => customer5.id, "film_id" => film2.id })
ticket8.save()

binding.pry
nil
